
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
    	
        return true;
    }
    public int add(int a, int b) {
    	return a+b;
    }
    public int substract(int a, int b) {
    	return a-b;
    }
}
