/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.*;

import java.util.List;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Assert;

public class LibraryTest {
	WebDriver driver; 
@Before public void openBrowser() {
	driver = new ChromeDriver();
	driver.manage().window().maximize();
}
/*
@Test     public void ChromeTest() throws InterruptedException {
	
	
	driver.get("http://www.google.com");
	WebElement barreRecherche = driver.findElement(By.id("lst-ib"));
	//System.out.println("id=" + barreRecherche.toString() );
	//barreRecherche.sendKeys("Coupe du monde" + Keys.ENTER);
	barreRecherche.sendKeys("Coupe du monde");
	/*
	WebElement button = driver.findElement(By.name("btnK"));
	button.click();
	*/
	/*
	List<WebElement> buttons = driver.findElements(By.className("lsb"));
	buttons.get(0).click();
	
	WebElement imageCoupe = driver.findElement(By.id("dimg_29"));
	

	Assert.assertTrue(imageCoupe.isDisplayed());
	
	Thread.sleep(5000);
	
	
}
*/
@Test     public void ChromeTest2() throws InterruptedException {
    	
    	
    	driver.get("https://en.wikipedia.org/wiki/Main_Page");
    	WebElement barreRecherche = driver.findElement(By.id("searchInput"));

    	barreRecherche.sendKeys("World Cup" + Keys.ENTER );
    	
    	
    	WebElement lienFifa = driver.findElement(By.xpath("//*[@id=\"mw-content-text\"]/div/p[1]/a"));
    	lienFifa.click();
    	
		Thread.sleep(5000);
		
    	
		String resultat_reel=driver.findElement(By.xpath("//*[@id=\"firstHeading\"]")).getText() ;
    	//Assert.assertEquals(resultat_reel,"FIFA World Cup");
    	Assert.fail();
    	
}

@After 	public void closeBrowser() {
	driver.quit();   // closes window and process
		
	}
	
}
